main: su.nightexpress.coinsengine.CoinsEnginePlugin
version: '${project.version}'
name: CoinsEngine
author: NightExpress
desciption: A lightweight and modern multi-currency and an economy plugin.
load: STARTUP
api-version: 1.21
depend: [ nightcore ]
softdepend:
  - PlaceholderAPI
  - PlayerPoints